import "@aws-amplify/ui-react/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ConfigureAmplifyClientSide from "../../components/ConfigureAmplify";
import  AuthProvider from "../components/Auth/AuthProvider/AuthProvider";
import { Navigation } from "../components/Navigation/Navigation";
import ThemeProviderComponent from '../components/ThemeProviderComponent/ThemeProviderComponent';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConfigureAmplifyClientSide />
      <ThemeProviderComponent>
      <AuthProvider>   
               
            <Navigation></Navigation>
            <main className="main-content">
              {children}
              </main>
      </AuthProvider>  
      </ThemeProviderComponent> 

      </body>
    </html>
  );
}
